version: '2'
services:

  videofaces-frontend:
    image: dsevilla/videofaces-frontend:1.0
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=development
      - SQL_SERVER=videofaces-mysql
      - GRPC_SERVER=videofaces-grpc
      - GRPC_SERVER_PORT=50051


  videofaces-mysql:
    command: --max_allowed_packet=1024M
    build: videofaces-mysql/.
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=videofaces

  backend-rest:
    image: dsevilla/videofaces-backend-rest:1.0
    ports:
      - 8080:8080
    environment:
      - SQL_SERVER=videofaces-mysql
      - GRPC_SERVER=videofaces-grpc
      - GRPC_SERVER_PORT=50051

  videofaces-grpc:
    image: dsevilla/videofaces-backend-grpc:1.0
    ports:
      - 50051
    environment:
      - SQL_SERVER=videofaces-mysql
      - GRPC_SERVER=videofaces-grpc
      - GRPC_SERVER_PORT=50051


