FROM python:3.10-slim

RUN mkdir -p /ssdd-frontend

# We copy just the requirements.txt first to leverage Docker cache
COPY requirements.txt /ssdd-frontend

WORKDIR /ssdd-frontend

RUN pip install -r requirements.txt

ENV FLASK_APP="app/app.py"
ENV FLASK_DEBUG=false
ENV PORT=5010

EXPOSE 5010

CMD [ "flask", "run", "--host=0.0.0.0", "--port=5010" ]
