name: Makefile CI

on:
  push:
    branches: [ '25-26', '24-25', '23-24', 'v*' ]
  pull_request:
    branches: [ '25-26', '24-25', '23-24', 'v*' ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17, 21, 25]
    env:
      JAVA_VERSION: ${{ matrix.java-version }}
    defaults:
      run:
        working-directory: proyecto
    steps:

      - name: Checkout the repo.
        uses: actions/checkout@v6

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: 'maven'

      - name: build proyecto
        run: make
